# Generated by Django 3.0.6 on 2020-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_avisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
