# Generated by Django 3.0.6 on 2020-05-20 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0010_auto_20200520_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 17, 45, 48, 224202, tzinfo=utc)),
        ),
    ]
