# Generated by Django 3.0.6 on 2020-05-20 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0011_auto_20200520_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 17, 46, 23, 345211, tzinfo=utc)),
        ),
    ]
