# Generated by Django 3.0.6 on 2020-05-20 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0014_auto_20200520_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 18, 36, 47, 715195, tzinfo=utc)),
        ),
    ]
