# Generated by Django 3.0.6 on 2020-05-21 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0016_auto_20200520_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 11, 52, 36, 513590, tzinfo=utc)),
        ),
    ]
