# Generated by Django 3.0.3 on 2020-05-23 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0017_auto_20200521_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 1, 53, 40, 495552, tzinfo=utc)),
        ),
    ]
