"""
Django settings for prueba project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from .base import *


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []





# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_ce',
        'USER':'florm2496',
        'PASSWORD':'pan1994245',
        'HOST':'localhost',
        'PORT':'5432',
    }
}




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR.child('static')]

MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR.child('media')


CKEDITOR_UPLOAD_PATH='uploads/'
CKEDITOR_UPLOAD_BACKEND='pillow'
CKEDITOR_JQUERY_URL='https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'
CKEDITOR_CONFIGS={
    'default':{
        'toolbar':'Custom',
        'toolbar_Custom':[
            ['Bold' , 'Italic' ,'Underline'],
            ['NumberedList' ,'BullstedList' , '-','Outdent','-','Justifyl'],
            ['TextColor','Format','FontSize','Link'],
            ['Smiley' , 'Image','Iframe'],
            ['RemoveFormat' , 'Source'],
        ],
        'stylesSet':[

        ],
    }

}
# EMAIL SETTINGS
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = get_secret('EMAIL')
# EMAIL_HOST_PASSWORD = get_secret('PASS_EMAIL')
# EMAIL_PORT = 587