# Generated by Django 3.0.6 on 2020-05-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepto', to='prueba1.Departamento')),
            ],
            options={
                'verbose_name': 'subdepto',
                'verbose_name_plural': 'subdeptos',
            },
        ),
    ]
