# Generated by Django 3.0.6 on 2020-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdepto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepto',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisiones'},
        ),
    ]
