# Generated by Django 3.0.6 on 2020-05-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subdepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='depto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subdepto',
        ),
    ]
