# Generated by Django 3.0.6 on 2020-05-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200520_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='depto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subdepto',
        ),
    ]
