# Generated by Django 3.0.3 on 2020-05-23 01:53

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'escuela',
                'verbose_name_plural': 'escuelas',
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2020, 5, 23, 1, 53, 40, 518554, tzinfo=utc))),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_emergencia', to='emergencias.Categoria')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_emergencia', to='emergencias.Escuela')),
            ],
            options={
                'verbose_name': 'emergencia',
                'verbose_name_plural': 'emergencias',
            },
        ),
    ]
